<?php

/**
 * WjrArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    wjr
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WjrArticle extends BaseWjrArticle
{
	public function getTitleSlug()
	{
	  return Wjr::slugify($this->getTitle());
	}
	
	
	/*
	// uzywane przez backend/article
	// dostep przez zmienna category_name
	public function getCategoryName()
	{
		$id = $this->getCategoryId();
		
		$q = Doctrine_Query::create()
		  ->select('c.name AS c_name')
		  ->from('WjrCategory c')
		  ->where('c.id = ?', $this->getCategoryId());
		  
		return $q->execute()->getFirst();
	}
	*/
}