<?php

/**
 * WjrCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WjrCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WjrCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WjrCategory');
    }
}