<?php

/**
 * WjrInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WjrInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WjrInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WjrInfo');
    }
}