<?php

/**
 * WjrPigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WjrPigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WjrPigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WjrPig');
    }
}