<?php

/**
 * WjrTripTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WjrTripTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WjrTripTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WjrTrip');
    }
	
	public function getTrips($id = null)
	{
		$q = Doctrine_Query::create()
		  ->select('t.*, gpx.name AS gpx_name, gpx.title AS gpx_title, gpx.points AS gpx_points, gpx.description AS gpx_description, gpx.lat_start AS gpx_lat_start, gpx.lon_start AS gpx_lon_start, gpx.lat_stop AS gpx_lat_stop, gpx.lon_stop AS gpx_lon_stop')
		  ->from('WjrTrip t')
		  ->where('t.is_activated = ?', 1)
		  ->leftJoin('t.WjrTrack gpx')
		  ->orderBy('t.created_at DESC')
		  ->limit(sfConfig::get('app_max_trips'));
		
		if (!is_null($id))
		{
			$q->andWhere('t.id = ?', $id);
			// getFirst() zwraca pierwszy rekord z kolekcji;
			// nawet pomimo braku $id kolekcja nigdy nie jest pusta!
			// ale wtedy dzieki getFirst() zwraca pusty obiekt;
			return $q->execute()->getFirst();
		}
		
		return $q;
	}
	
	// dla apps/backend/modules/article/config/generator.yml
	// zmiejsza liczbe zapytan o kategorie, tworzy obiekt kategorii
	public function retrieveBackendTripList(Doctrine_Query $q)
	{
	  $rootAlias = $q->getRootAlias();
	 
	  $q->leftJoin($rootAlias . '.WjrTrack t');
	 
	  return $q;
	}
}