<?php

/**
 * WjrTrackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WjrTrackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WjrTrackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WjrTrack');
    }
}